[font]
size = 8.0
offset = { x = 0, y = 2 }

[font.normal]
family = "RobotoMono Nerd Font"

[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true

[colors.primary]
background = "#161821"
foreground = "#c6c8d1"

[colors.normal]
black   = "#161821"
red     = "#e27878"
green   = "#b4be82"
yellow  = "#e2a478"
blue    = "#84a0c6"
magenta = "#a093c7"
cyan    = "#89b8c2"
white   = "#c6c8d1"

[colors.bright]
black   = "#6b7089"
red     = "#e98989"
green   = "#c0ca8e"
yellow  = "#e9b189"
blue    = "#91acd1"
magenta = "#ada0d3"
cyan    = "#95c4ce"
white   = "#d2d4de"

[scrolling]
history = 100000

[shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux a -t 0 || tmux"]
